#! /usr/bin/env python3

"""
Check if the necessary AMD Infinity Storage (AIS) components are installed

If all necessary components are installed the program exits with exit code 0.
If components are missing the program exits with a non-zero exit code.
"""

import argparse
import ctypes
import ctypes.util
import sys


def hip_runtime_supports_ais():
    """
    Check if hipAmdFileRead and hipAmdFileWrite are available in HIP
    """
    hip_path = ctypes.util.find_library("amdhip64")
    if hip_path is None:
        return False

    hip = ctypes.CDLL(hip_path)

    hipError_t = ctypes.c_int
    hipDriverProcAddressQueryResult = ctypes.c_int

    hip.hipRuntimeGetVersion.argtypes = [ctypes.POINTER(ctypes.c_int)]
    hip.hipRuntimeGetVersion.restype = hipError_t

    hip.hipGetProcAddress.argtypes = [
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_void_p),
        ctypes.c_int,
        ctypes.c_uint64,
        ctypes.POINTER(hipDriverProcAddressQueryResult),
    ]
    hip.hipGetProcAddress.restype = hipError_t

    hip.hipGetErrorString.argtypes = [hipError_t]
    hip.hipGetErrorString.restype = ctypes.c_char_p

    version = ctypes.c_int()
    err = hip.hipRuntimeGetVersion(ctypes.byref(version))
    if err != 0:
        err_str = hip.hipGetErrorString(err).decode("utf-8")
        print(
            f"hipRuntimeGetVersion failed with err code {err} ({err_str})",
            file=sys.stderr,
        )
        return False

    for symbol in [b"hipAmdFileWrite", b"hipAmdFileRead"]:
        func_ptr = ctypes.c_void_p()
        symbol_status = hipDriverProcAddressQueryResult()
        err = hip.hipGetProcAddress(
            symbol,
            ctypes.byref(func_ptr),
            version.value,
            0,
            ctypes.byref(symbol_status),
        )
        if err != 0:
            if symbol_status.value != 1:
                symbol = symbol.decode("utf-8")
                err_str = hip.hipGetErrorString(err).decode("utf-8")
                print(
                    f"hipGetProcAddress({symbol}) failed with err code"
                    f" {err} ({err_str}) and symbolStatus"
                    f" {symbol_status.value}",
                    file=sys.stderr,
                )
            return False

    return True


def amdgpu_supports_ais():
    """
    Check if kfd_ais_rw_file is in the kernel's symbol table
    """
    with open("/proc/kallsyms", "r") as kallsyms:
        for line in kallsyms:
            if "kfd_ais_rw_file" in line:
                return True
    return False


def main(args):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-q", "--quiet", action="store_true", help="Silence regular output"
    )
    args = parser.parse_args()

    component_support = [
        ("HIP Runtime", hip_runtime_supports_ais()),
        ("amdgpu", amdgpu_supports_ais()),
    ]

    if not args.quiet:
        print("AIS support in:")
        for name, supported in component_support:
            print(f"  {name:>12}: {'true' if supported else 'false'}")

    return int(not all(supported for (_, supported) in component_support))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
