name: build_and_test # Mono-workflow - May be advantageous to split up
run-name: Build, Test, and Analyze AIS
env:
  AIS_GHA_CMD_FILES_DOCKER_DIR: /root/github
  AIS_MOUNT_PATH: /mnt/ais/ext4
on:
  workflow_call:
    inputs:
      ci_image:
        required: true
        type: string
      platform:
        required: true
        type: string
permissions:
  contents: read
  packages: read
jobs:
  compile_on_AMD:
    outputs:
      ais_hipfile_version: ${{ steps.pkg-metadata.outputs.AIS_HIPFILE_VERSION }}
    runs-on: [ubuntu-24.04]
    steps:
      - name: Set early AIS CI environment variables
        run: |
          echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
          echo "AIS_GHA_CMD_FILES_DIR=${GITHUB_ENV%/*}" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}" >> "$GITHUB_ENV"
      - name: Fetching code repository...
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          path: hipFile
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Detach the container and run separate commands to it.
      # Thus we can make separate explicit steps in the Github CI
      # as if we were able to parameterize the container image in the first place.
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v "${AIS_GHA_CMD_FILES_DIR}:${{ env.AIS_GHA_CMD_FILES_DOCKER_DIR }}" \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Make copy of the code repository and create build directories
        # Single quotes necessary to ensure string/command substitutions happen
        # in the container and not on the host.
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/hipFile/build
            '
      - name: Generate build files for hipFile targeting the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=amdclang++ \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=amd \
                -DBUILD_AIS_DOCS=ON \
                -DBUILD_CODE_COVERAGE=ON \
                ..
            '
      - name: Build hipFile for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Test hipFile for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ctest -V -L "unit" --parallel
            '
      - name: Generate coverage summary (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              export PATH="/opt/rocm/llvm/bin:$PATH"
              ../util/llvm-coverage.sh
              printf "# Code Coverage\n"
              printf "\`\`\`\n"
              cat coverage-report.txt
              printf "\`\`\`\n"
            ' >> $GITHUB_STEP_SUMMARY
        if: ${{ inputs.platform == 'ubuntu' }}
      - name: Create hipFile package
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cpack -G ${{ inputs.platform == 'ubuntu' && 'DEB' || 'RPM' }}
            '
      # CI is unable to peer into CMake to capture this data ahead of time.
      # We should only produce a single package so we can use a glob pattern
      # to complete the relative path to select the package.
      # For now, hardcode the glob pattern to the default DEV release package name.
      # (We will also hardcode arch as well.)
      - name: Capture package metadata
        id: pkg-metadata
        run: |
          docker exec \
            -e "AIS_GITHUB_OUTPUT=${{ env.AIS_GHA_CMD_FILES_DOCKER_DIR }}/${GITHUB_OUTPUT##*/}" \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              echo "AIS_HIPFILE_VERSION=$(
                ${{
                  inputs.platform == 'ubuntu' &&
                  'dpkg-deb -f hipfile-dev*.deb "Version"' ||
                  'rpm -qp --qf "%{VERSION}" hipfile-devel*.rpm'
                }}
              )" >> "${AIS_GITHUB_OUTPUT}"
            '
      # This information will be nice to have for debugging CPack configuration.
      - name: Print package metadata for debugging.
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              echo "$(
                ${{
                  inputs.platform == 'ubuntu' &&
                  'dpkg-deb -I hipfile-dev*.deb' ||
                  'rpm -qpi --requires hipfile-devel*.rpm'
                }}
              )"
            '
      - name: Validate Metadata stored correctly
        run: |
          echo "hipFile package version: ${{ steps.pkg-metadata.outputs.AIS_HIPFILE_VERSION }}"
          if [[ -z "${{ steps.pkg-metadata.outputs.AIS_HIPFILE_VERSION }}" ]]; then exit 1; fi
      - name: Test installing the hipFile package.
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ${{
                inputs.platform == 'ubuntu' && 'apt install -y ./hipfile-dev*.deb' ||
                inputs.platform == 'rocky' && 'dnf install -y ./hipfile-devel*.rpm' ||
                inputs.platform == 'suse' && 'zypper install -y --allow-unsigned-rpm ./hipfile-devel*.rpm' ||
                'echo "Unknown platform."; exit 1'
              }}
            '
      - name: Clean CMake build directories
        run: |
          docker exec \
            -t \
            -w /ais/hipFile \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              rm -rf build/*
            '
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
  compile_on_AMD_other:
    runs-on: [ubuntu-24.04]
    strategy:
      fail-fast: false
      matrix:
        alternate_compilers:
          - clang++
          - g++
    steps:
      - name: Set early AIS CI environment variables
        run: |
          echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
          echo "AIS_SAFE_COMPILER_NAME=$(echo ${{ matrix.alternate_compilers}} | sed 's|[\+]|plus|g')" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}_${AIS_SAFE_COMPILER_NAME}" >> "$GITHUB_ENV"
      - name: Fetching code repository...
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          path: hipFile
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Make copy of the code repository and create build directories
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/hipFile/build
            '
      - name: Generate build files for hipFile targeting the AMD platform (${{ matrix.alternate_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=${{ matrix.alternate_compilers }} \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=amd \
                -DBUILD_AIS_DOCS=ON \
                ..
            '
      - name: Build hipFile for the AMD platform (${{ matrix.alternate_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
  AMD_system_tests:
    runs-on: [linux, AIS]
    needs: compile_on_AMD
    steps:
      - name: Set early AIS CI environment variables
        run: echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}" >> "$GITHUB_ENV"
      - name: Fetching hipFile repository...
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          path: hipFile
      - name: Fetching fio repository...
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          repository: ROCm/fio
          ref: hipFile
          path: fio
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Detach the container and run separate commands to it.
      # Thus we can make separate explicit steps in the Github CI
      # as if we were able to parameterize the container image in the first place.
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --device=/dev/kfd \
            --device=/dev/dri \
            --security-opt seccomp=unconfined \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Create hipfile IO test directory
        run: |
          docker exec -t ${AIS_CONTAINER_NAME} /bin/bash -c "mkdir -p /mnt/ais-fs/${AIS_CONTAINER_NAME}"
      - name: Make copy of the code repository and create build directories
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/hipFile/build
              mkdir /ais/fio/build
            '
      - name: Generate build files for hipFile targeting the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=amdclang++ \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=amd \
                -DBUILD_AIS_DOCS=ON \
                ..
            '
      - name: Build hipFile for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Run hipFile system tests for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ctest -V -L "system" --parallel
            '
      - name: Stress tests for hipFile targeting the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ctest -V -L "stress" --parallel
            '
      - name: hipFile fallback/POSIX IO test using aiscp
        run: |
          docker exec \
            -t \
            -w /mnt/ais-fs/${AIS_CONTAINER_NAME} \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              HIPFILE_FORCE_COMPAT_MODE=true
                /ais/hipFile/util/ci-aiscp-test.sh \
                /ais/hipFile/build/hipfile/examples/aiscp/aiscp
            '
      - name: Configure fio
        run: |
          docker exec \
            -t \
            -w /ais/fio/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ROCM=/opt/rocm \
              HIPFILE=/ais/hipFile \
              HIPFILELIB=${HIPFILE}/build/hipfile/src/amd_detail/ \
              HIP_PLATFORM=amd \
              CFLAGS="-I${ROCM}/include -I${HIPFILE}/hipfile/include" \
              LDFLAGS="-L${ROCM}/lib -L${HIPFILELIB} -Wl,-rpath,${HIPFILELIB}" \
              ../configure --enable-libhipfile
            '
      - name: Build fio
        run: |
          docker exec \
            -t \
            -w /ais/fio/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              make -j
            '
      - name: hipFile fallback/POSIX IO test using fio
        run: |
          docker exec \
            -t \
            -w /mnt/ais-fs/${AIS_CONTAINER_NAME} \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              HIPFILE_FORCE_COMPAT_MODE=true \
                /ais/fio/build/fio \
                /ais/hipFile/util/fio/write-read-verify.fio
            '
      - name: Destroy hipfile IO test directory
        if: ${{ always() }}
        run: |
          docker exec -t ${AIS_CONTAINER_NAME} /bin/bash -c "rm -fr /mnt/ais-fs/${AIS_CONTAINER_NAME}"
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
  compile_on_NVIDIA:
    runs-on: [ubuntu-24.04]
    strategy:
      fail-fast: false
      matrix:
        supported_compilers:
          - g++
          - clang++
    steps:
      - name: Set early AIS CI environment variables
        run: |
          echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
          echo "AIS_SAFE_COMPILER_NAME=$(echo ${{ matrix.supported_compilers }} | sed 's|[\+]|plus|g')" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}_${AIS_SAFE_COMPILER_NAME}" >> "$GITHUB_ENV"
      - name: Fetching code repository...
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          path: hipFile
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Detach the container and run separate commands to it.
      # Thus we can make separate explicit steps in the Github CI
      # as if we were able to parameterize the container image in the first place.
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Make copy of the code repository and create build directories
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/hipFile/build
            '
      - name: Generate build files for hipFile targeting the NVIDIA platform (${{ matrix.supported_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=${{ matrix.supported_compilers }} \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=nvidia \
                -DBUILD_AIS_DOCS=ON \
                ..
            '
      - name: Build hipFile for the NVIDIA platform (${{ matrix.supported_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/hipFile/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Clean CMake build directories
        run: |
          docker exec \
            -t \
            -w /ais/hipFile \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              rm -rf build/*
            '
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
### Disable until NVIDIA runners come back
#  Run_hipFile_NVIDIA:
#    uses: ./.github/workflows/hipfile-nvidia.yml
#    needs: build_AIS_image
#    with:
#      platform: ${{inputs.platform}}
