name: build_and_test # Mono-workflow - May be advantageous to split up
run-name: Build, Test, and Analyze AIS
env:
  AIS_MOUNT_PATH: /mnt/ais/ext4
on:
  workflow_call:
    inputs:
      ci_image:
        required: true
        type: string
      platform:
        required: true
        type: string
permissions:
  contents: read
  packages: read
jobs:
  compile_on_AMD:
    runs-on: [ubuntu-24.04]
    steps:
      - name: Set early AIS CI environment variables
        run: echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}" >> "$GITHUB_ENV"
      - name: Fetching code repository...
        uses: actions/checkout@v6
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Detach the container and run separate commands to it.
      # Thus we can make separate explicit steps in the Github CI
      # as if we were able to parameterize the container image in the first place.
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Make copy of the code repository and create build directories
        # Single quotes necessary to ensure string/command substitutions happen
        # in the container and not on the host.
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/build
            '
      - name: Generate build files for hipFile targeting the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=amdclang++ \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=amd \
                -DBUILD_AIS_DOCS=ON \
                -DAIS_USE_CLANG_TIDY=ON \
                -DBUILD_CODE_COVERAGE=ON \
                ..
            '
      - name: Build hipFile for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Test hipFile for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ctest -V -L "unit" --parallel
            '
      - name: Generate coverage summary (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              export PATH="/opt/rocm/llvm/bin:$PATH"
              ../util/llvm-coverage.sh
              printf "# Code Coverage\n"
              printf "\`\`\`\n"
              cat coverage-report.txt
              printf "\`\`\`\n"
            ' >> $GITHUB_STEP_SUMMARY
        if: ${{ inputs.platform == 'ubuntu' }}
      - name: Clean CMake build directories
        run: |
          docker exec \
            -t \
            -w /ais \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              rm -rf build/*
            '
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
  compile_on_AMD_other:
    runs-on: [ubuntu-24.04]
    strategy:
      fail-fast: false
      matrix:
        alternate_compilers:
          - clang++
          - g++
    steps:
      - name: Set early AIS CI environment variables
        run: |
          echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
          echo "AIS_SAFE_COMPILER_NAME=$(echo ${{ matrix.alternate_compilers}} | sed 's|[\+]|plus|g')" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}_${AIS_SAFE_COMPILER_NAME}" >> "$GITHUB_ENV"
      - name: Fetching code repository...
        uses: actions/checkout@v6
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Make copy of the code repository and create build directories
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/build
            '
      - name: Generate build files for hipFile targeting the AMD platform (${{ matrix.alternate_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=${{ matrix.alternate_compilers }} \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=amd \
                -DBUILD_AIS_DOCS=ON \
                ..
            '
      - name: Build hipFile for the AMD platform (${{ matrix.alternate_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
  AMD_system_tests:
    runs-on: [linux, AIS]
    needs: compile_on_AMD
    steps:
      - name: Set early AIS CI environment variables
        run: echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}" >> "$GITHUB_ENV"
      - name: Fetching code repository...
        uses: actions/checkout@v6
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Detach the container and run separate commands to it.
      # Thus we can make separate explicit steps in the Github CI
      # as if we were able to parameterize the container image in the first place.
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --device=/dev/kfd \
            --device=/dev/dri \
            --security-opt seccomp=unconfined \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Make copy of the code repository and create build directories
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/build
            '
      - name: Generate build files for hipFile targeting the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=amdclang++ \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=amd \
                -DBUILD_AIS_DOCS=ON \
                ..
            '
      - name: Build hipFile for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Run hipFile system tests for the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ctest -V -L "system" --parallel
            '
      - name: Stress tests for hipFile targeting the AMD platform (amdclang++)
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              ctest -V -L "stress" --parallel
            '
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
  compile_on_NVIDIA:
    runs-on: [ubuntu-24.04]
    strategy:
      fail-fast: false
      matrix:
        supported_compilers:
          - g++
          - clang++
    steps:
      - name: Set early AIS CI environment variables
        run: |
          echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "$GITHUB_ENV"
          echo "AIS_SAFE_COMPILER_NAME=$(echo ${{ matrix.supported_compilers }} | sed 's|[\+]|plus|g')" >> "$GITHUB_ENV"
      - name: Set AIS CI container name
        run: |
          echo "AIS_CONTAINER_NAME=${AIS_PR_NUMBER}_${{ github.job }}_${{ inputs.platform }}_${AIS_SAFE_COMPILER_NAME}" >> "$GITHUB_ENV"
      - name: Fetching code repository...
        uses: actions/checkout@v6
      - name: Authenticating to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Detach the container and run separate commands to it.
      # Thus we can make separate explicit steps in the Github CI
      # as if we were able to parameterize the container image in the first place.
      - name: Starting Docker Container
        run: |
          docker run \
            -dt \
            --rm \
            --pull always \
            -v ${GITHUB_WORKSPACE}:/mnt/ais:ro \
            -v ${{ env.AIS_MOUNT_PATH }}:/mnt/ais-fs \
            --name ${AIS_CONTAINER_NAME} \
            ${{ inputs.ci_image }}
      - name: Make copy of the code repository and create build directories
        run: |
          docker exec \
            -t \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cp -R /mnt/ais /ais
              mkdir /ais/build
            '
      - name: Generate build files for hipFile targeting the NVIDIA platform (${{ matrix.supported_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake \
                -DCMAKE_CXX_COMPILER=${{ matrix.supported_compilers }} \
                -DCMAKE_CXX_FLAGS="-Werror" \
                -DCMAKE_HIP_PLATFORM=nvidia \
                -DBUILD_AIS_DOCS=ON \
                ..
            '
      - name: Build hipFile for the NVIDIA platform (${{ matrix.supported_compilers }})
        run: |
          docker exec \
            -t \
            -w /ais/build \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              cmake --build . --parallel
            '
      - name: Clean CMake build directories
        run: |
          docker exec \
            -t \
            -w /ais \
            ${AIS_CONTAINER_NAME} \
            /bin/bash -c '
              rm -rf build/*
            '
      - name: Cleanup & Stop the Docker container
        if: ${{ always() }}
        run: |
          docker stop ${AIS_CONTAINER_NAME}
### Disable until NVIDIA runners come back
#  Run_hipFile_NVIDIA:
#    uses: ./.github/workflows/hipfile-nvidia.yml
#    needs: build_AIS_image
#    with:
#      platform: ${{inputs.platform}}
