# Run ShellCheck (https://www.shellcheck.net/) over all shell scripts
# in the repository

name: ShellCheck
on: pull_request
permissions:
  contents: read
jobs:
  shellcheck:
    name: Run ShellCheck over shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 #v4.1.7
      - uses: ludeeus/action-shellcheck@8b8e6e6e2c1b7e6cfa2a8b1b3e6b7e6e6e6e6e6e #v2.0.0
